### ISSUE TITLE
What is the right way to override prefix?

### ISSUE THREAD

**Issue by mrTall** [Genaker/laragento#10]
Hi, thanks for wonderful package!
What is the good way to override magento prefix on the DB class?
Thank you

**Comment by Genaker** [comment]
Check src/DB.php

Prefix it is DB class parameter

![image](https://github.com/Genaker/laragento/assets/9213670/df7a88ae-3389-4a17-abde-ae9a76706622)

Also override using OOP inheritance. Just extend it. You have Laragento/DB you will have YorProject/DB 

Also you can use regular Magento override if you are using as part of the Magento core

**Comment by Genaker** [comment]
It also has getMageConfig(Path) method to read Magento config
